#!/bin/bash
# 测试文件

data=$1
outfile=$2

for i in $data; do
    A="${i%-*}"; B="${i#*-}"
    A1="${A##*.}"; B1="${B##*.}"
    diff=$(($B1 - $A1))
    A2="${A##*.}"
    echo $A $B $A1 $B1 $diff
    echo $A | awk -F "." '{print $2}'
    
    if [ "$diff" == "0" ]; then
            echo $A >> $outfile
    elif [ "$diff" -gt "0" -a "$diff" ]; then
            echo $A >> $outfile
            for ((a=1; a<=$diff; a++)); do
                    count=$(($A1 + $a))
                    echo "${A%.*}.$count" >> $outfile
            done
    else
            echo "${A%.*}.0/24" >> $outfile
    fi
done