# 指定基础镜像及版本
FROM python:3.8-slim-buster
# 创作权署名
LABEL author=igamenine
# 将当前目录下文件拷贝到镜像对应目录，如果没写默认当前目录
ADD . /app
# 指定镜像内工作路径（如没有则会自动创建）
WORKDIR /app
# 拷贝本地文件至镜像路径 第一个参数是本地文件，第二个参数是镜像路径
COPY . .
# 镜像初始化预执行命令，符合镜像系统语法即可
RUN pip3 install -r requirements.txt
# 容器初始化执行命令
CMD python3 app.py
# cmd ["python3", "app.py"] #有两种写法，看自己习惯
# 可挂载卷，在dockerfile中定义了这个路径才可以在启动时定义挂载内容
VOLUME /app
# VOLUME ["/app", "/home/app"] #有两种写法，看自己习惯
