-- GROUP BY子句有个缺点，就是返回的结果集中只有合计数据，而没有原始的详细记录。
-- 如果想在SQL SERVER中完成这项工作，可以使用COMPUTE BY子句。
-- COMPTE生成合计作为附加的汇总列出现在结果集的最后。
-- 当与BY一起使用时，COMPUTE 子句在结果集内生成控制中断和分类汇总。
-- 转自https://www.jianshu.com/p/f428c5ea5540
