{
 "title": "MySQL Panorama",
 "description": "Simple mysql dashboard.",
 "tags": [
  "mysql",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(mysql_global_status_connections, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Table Open Cache",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-mysql_global_status_table_open_cache_misses{instance=~\"$Instance\"}/mysql_global_status_table_open_cache_hits{instance=~\"$Instance\"}*100",
     "legendFormat": "Efficiency"
    }
   ]
  },
  {
   "title": "InnoDB Boffer Pool",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-sum(mysql_global_status_buffer_pool_pages{instance=~\"$Instance\",state=\"free\"})/sum(mysql_global_status_buffer_pool_pages{instance=~\"$Instance\",state!=\"old\"})*100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=~\"$Instance\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "mysql_global_variables_max_connections{instance=~\"$Instance\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Select executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=~\"$Instance\",command=\"select\"}[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "InnoDB Disk Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_written{instance=~\"$Instance\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Incoming Network traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{instance=~\"$Instance\"}[1m])",
     "legendFormat": "Recieved"
    }
   ]
  },
  {
   "title": "Insert executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=~\"$Instance\",command=\"insert\"}[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "InnoDB Disk Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_read{instance=~\"$Instance\"}[1m])",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Outgoing Network traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_sent{instance=~\"$Instance\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}